# Generated by Django 5.2.7 on 2026-03-18 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipio',
            name='rank_nacional_00',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='municipio',
            name='total_nacional_00',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
