# Generated by Django 5.2.7 on 2026-03-06 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrescimentoMedioPorte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_referencia', models.IntegerField()),
                ('porte', models.CharField(max_length=50)),
                ('receita', models.FloatField(blank=True, null=True)),
                ('populacao', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CrescimentoMedioUf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano_referencia', models.IntegerField()),
                ('uf', models.CharField(max_length=2)),
                ('receita', models.FloatField(blank=True, null=True)),
                ('populacao', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
