# Generated by Django 5.2.7 on 2026-01-29 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título da Matéria')),
                ('data', models.DateField(verbose_name='Data de Publicação')),
                ('imagem', models.ImageField(upload_to='noticias/', verbose_name='Imagem de Capa')),
                ('tag', models.CharField(max_length=50, verbose_name='Categoria (Tag)')),
                ('link', models.URLField(blank=True, max_length=500, null=True, verbose_name='Link de Destino')),
            ],
            options={
                'verbose_name': 'Notícia',
                'verbose_name_plural': 'Notícias',
                'ordering': ['-data'],
            },
        ),
    ]
