# Generated by Django 5.2.7 on 2026-03-05 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contamaisespecificapercentil',
            old_name='icms_estadual',
            new_name='imposto_icms_estadual',
        ),
        migrations.RenameField(
            model_name='contamaisespecificapercentil',
            old_name='icms_regional',
            new_name='imposto_icms_regional',
        ),
        migrations.RenameField(
            model_name='contamaisespecificapercentil',
            old_name='ipva_estadual',
            new_name='imposto_ipva_estadual',
        ),
        migrations.RenameField(
            model_name='contamaisespecificapercentil',
            old_name='ipva_regional',
            new_name='imposto_ipva_regional',
        ),
        migrations.RenameField(
            model_name='contamaisespecificapercentil',
            old_name='renda_estadual',
            new_name='imposto_renda_estadual',
        ),
        migrations.RenameField(
            model_name='contamaisespecificapercentil',
            old_name='renda_regional',
            new_name='imposto_renda_regional',
        ),
    ]
