# Generated by Django 5.2.7 on 2026-02-19 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_noticia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='municipio',
            old_name='decil23',
            new_name='decil24',
        ),
        migrations.RenameField(
            model_name='municipio',
            old_name='percentil',
            new_name='percentil00',
        ),
        migrations.RenameField(
            model_name='municipio',
            old_name='percentil_n',
            new_name='percentil00_n',
        ),
        migrations.RenameField(
            model_name='municipio',
            old_name='quintil23',
            new_name='percentil24',
        ),
        migrations.RenameField(
            model_name='municipio',
            old_name='populacao23',
            new_name='populacao24',
        ),
        migrations.RenameField(
            model_name='municipio',
            old_name='rc_2023',
            new_name='rc_2000',
        ),
        migrations.RenameField(
            model_name='municipio',
            old_name='rc_23_pc',
            new_name='rc_2024',
        ),
        migrations.AddField(
            model_name='municipio',
            name='percentil24_n',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='municipio',
            name='quintil24',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='municipio',
            name='rc_24_pc',
            field=models.FloatField(null=True),
        ),
    ]
