# Generated by Django 5.2.7 on 2026-02-19 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_decil23_municipio_decil24_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipio',
            name='cadunico',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='municipio',
            name='pib',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
