# Generated by Django 5.2.7 on 2026-02-19 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_municipio_cadunico_municipio_pib'),
    ]

    operations = [
        migrations.AddField(
            model_name='contamaisespecifica',
            name='renda',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contamaisespecifica',
            name='transferencia_unia_fundeb',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contamaisespecificapercentil',
            name='renda_estadual',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contamaisespecificapercentil',
            name='renda_nacional',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contamaisespecificapercentil',
            name='renda_regional',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contamaisespecificapercentil',
            name='transferencia_uniao_fundeb_estadual',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contamaisespecificapercentil',
            name='transferencia_uniao_fundeb_nacional',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contamaisespecificapercentil',
            name='transferencia_uniao_fundeb_regional',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
