# Generated by Django 5.2.7 on 2026-02-19 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_contamaisespecifica_renda_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contamaisespecifica',
            old_name='transferencia_unia_fundeb',
            new_name='transferencia_uniao_fundeb',
        ),
    ]
