# Generated by Django 5.2.7 on 2026-02-19 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_rename_transferencia_unia_fundeb_contamaisespecifica_transferencia_uniao_fundeb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contamaisespecificapercentil',
            name='outros_impostos_nacional',
            field=models.FloatField(default=0),
        ),
    ]
