# Generated by Django 5.2.7 on 2026-02-19 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_contamaisespecificapercentil_outros_impostos_nacional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contamaisespecificapercentil',
            name='outros_impostos_regional',
            field=models.FloatField(default=0),
        ),
    ]
