# Generated by Django 5.2.7 on 2026-02-20 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_contamaisespecificapercentil_outros_impostos_nacional_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contamaisespecifica',
            old_name='renda',
            new_name='imposto_renda',
        ),
    ]
