# Generated by Django 5.2.7 on 2026-02-23 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_rename_renda_contamaisespecifica_imposto_renda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='municipio',
            name='cadunico',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='decil00',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='decil24',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='percentil00',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='percentil00_n',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='percentil24',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='percentil24_n',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='pib',
            field=models.FloatField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='populacao00',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='quintil00',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='quintil24',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='rank_estadual',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='rank_faixa',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='rank_nacional',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='rc_00_pc',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='rc_2000',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='rc_2024',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='rc_24_pc',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='total_estadual',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='total_faixa',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='municipio',
            name='total_nacional',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
