# Generated by Django 5.2.7 on 2026-02-23 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_municipio_cadunico_alter_municipio_decil00_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='municipio',
            name='pib',
        ),
        migrations.AddField(
            model_name='municipio',
            name='cadunico_rank_estadual',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='municipio',
            name='cadunico_rank_faixa',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='municipio',
            name='cadunico_rank_nacional',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='municipio',
            name='cadunico_total_estadual',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='municipio',
            name='cadunico_total_faixa',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='municipio',
            name='cadunico_total_nacional',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='municipio',
            name='populacao24_rank_estadual',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='municipio',
            name='populacao24_rank_faixa',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='municipio',
            name='populacao24_rank_nacional',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='municipio',
            name='populacao24_total_estadual',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='municipio',
            name='populacao24_total_faixa',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='municipio',
            name='populacao24_total_nacional',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
